# .github/workflows/main.yml

name: Daily Task

on:
  schedule:
    - cron: "50 23 * * *"  # UTC 기준. 한국시간 오전 8시 55분
  workflow_dispatch:

jobs:
  login-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 libnss3 libxss1 libappindicator1 libindicator7
        sudo apt-get install -y chromium-browser
        pip install -r requirements.txt

    - name: Run login script
      env:
        LOGIN_ID: ${{ secrets.MY_ID }}
        LOGIN_PASSWORD: ${{ secrets.MY_PASSWORD }}
        LOGIN_URL: ${{ secrets.MY_LOGIN_URL }}
        SLACK_URL: ${{ secrets.MY_SLACK_URL }}
        BASE_URL: ${{ secrets.MY_BASE_URL }}
      run: python main.py
